YY_Npoi_ExportAndImport/Controllers/ExcelDataImportAndLookController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using Microsoft.AspNetCore.Http;
using YY_Dal;
using YY_Model;
using YY_Services;
using ActionResult = Microsoft.AspNetCore.Mvc.ActionResult;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using JsonResult = Microsoft.AspNetCore.Mvc.JsonResult;

namespace YY_NpoiExportAndImport.Controllers
{
    public class ExcelDataImportAndLookController : Controller
    {
        private readonly SchoolUserInfoContext _userInfoContext;

        private readonly NpoiExcelOperationService _excelOperationService;

        /// <summary>
        /// 依赖注入到ioc容器中
        /// </summary>
        /// <param name="schoolUserInfoContext"></param>
        /// <param name="excelOperationService"></param>
        public ExcelDataImportAndLookController(SchoolUserInfoContext schoolUserInfoContext, NpoiExcelOperationService excelOperationService)
        {
            _userInfoContext = schoolUserInfoContext;
            _excelOperationService = excelOperationService;
        }

        // GET: ExcelDataImportAndLook
        public ActionResult Index()
        {
            return View();
        }


       
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="page">当前页码</param>
        /// <param name="limit">显示条数</param>
        /// <param name="userName">用户姓名</param>
        /// <returns></returns>
        public JsonResult GetUserInfo(int page = 1, int limit =5, string userName = "") 
        {
            try
            {
                List<UserInfo> listData;
                var totalCount = 0;
                if (!string.IsNullOrWhiteSpace(userName))
                {
                    listData = _userInfoContext.UserInfos.Where(x => x.UserName.Contains(userName)).OrderByDescending(m => m.Id).ToList();//.OrderByDescending(m => m.Id).ToList();//.Skip((page - 1) * limit).Take(limit).ToList();
                    totalCount = _userInfoContext.UserInfos.Count(x => x.UserName.Contains(userName));
                }
                else
                {
                    listData = _userInfoContext.UserInfos.OrderByDescending(m => m.Id).ToList();//.Skip((page - 1) * limit).Take(limit).ToList(); 
                    totalCount = _userInfoContext.UserInfos.Count();
                }

                return Json(new { code = 0, count = totalCount, data = listData });
            }
            catch (Exception ex)
            {
                return Json(new { code = 1, msg = ex.Message });
            }
        }


        /// <summary>
        /// 数据导入页面
        /// </summary>
        /// <returns></returns>
        public ActionResult ImportPage()
        {
            return View();
        }

        /// <summary>
        /// 数据导入
        /// </summary>
        /// <param name="file">Form表单文件信息</param>
        /// <returns></returns>
        public JsonResult DataImport(IFormFile file)
        {

            var result = _excelOperationService.ExcelDataBatchImport(file, out string resultMsg);

            return Json(result ? new { code = 1, msg = resultMsg } : new { code = 0, msg = resultMsg });

        }


    }
}

YY_Npoi_ExportAndImport/Controllers/ExcelOperationController.cs
/**
 * Description:Excel数据导出
 */
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using YY_Dal;
using YY_Model;
using YY_Services;
using ActionResult = Microsoft.AspNetCore.Mvc.ActionResult;
using Controller = Microsoft.AspNetCore.Mvc.Controller;
using JsonResult = Microsoft.AspNetCore.Mvc.JsonResult;

namespace YY_NpoiExportAndImport.Controllers
{
    public class ExcelOperationController : Controller
    {
        private readonly NpoiExcelOperationService _excelExport;

        private readonly SchoolUserInfoContext _userInfoContext;
        public ExcelOperationController(SchoolUserInfoContext schoolUserInfoContext, NpoiExcelOperationService excelExport)
        {
            _userInfoContext = schoolUserInfoContext;
            _excelExport = excelExport;
        }

        /// <summary>
        /// 导出Excel文档展示界面
        /// </summary>
        /// <returns></returns>
        public IActionResult ExportExcelData()
        {
            return View();
        }

        /// <summary>
        /// Excel文档生成并导出
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DataExportSimple()
        {
            bool result = _excelExport.ExcelDataExport(out string resultMsg, out string excelFilePath);

            return Json(result == true ? new { code = 1, data = excelFilePath } : new { code = 0, data = resultMsg });
        }
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="page">当前页码</param>
        /// <param name="limit">显示条数</param>
        /// <param name="userName">用户姓名</param>
        /// <returns></returns>

        List<UserInfo> listData;

        public JsonResult GetUserInfo(int page = 1, int limit = 5, string userName = "")
        {
            try
            {
               
                var totalCount = 0;
                if (!string.IsNullOrWhiteSpace(userName))
                {
                    listData = _userInfoContext.UserInfos.Where(x => x.UserName.Contains(userName)).OrderByDescending(m => m.Id).ToList();//.OrderByDescending(m => m.Id).ToList();//.Skip((page - 1) * limit).Take(limit).ToList();
                    totalCount = _userInfoContext.UserInfos.Count(x => x.UserName.Contains(userName));
                }
                else
                {
                    listData = _userInfoContext.UserInfos.OrderByDescending(m => m.Id).ToList();//.Skip((page - 1) * limit).Take(limit).ToList(); 
                    totalCount = _userInfoContext.UserInfos.Count();
                }

                return Json(new { code = 0, count = totalCount, data = listData });
            }
            catch (Exception ex)
            {
                return Json(new { code = 1, msg = ex.Message });
            }
        }
        /// <summary>
        /// Excel文档生成并导出(数据库数据)
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DataExportOutPage()
        {
            listData = _userInfoContext.UserInfos.OrderByDescending(m => m.Id).ToList();
            bool result = _excelExport.DataExportOutPage(listData, out string resultMsg, out string excelFilePath);

            return Json(result == true ? new { code = 1, data = excelFilePath } : new { code = 0, data = resultMsg });
        }


    }
}

YY_Npoi_ExportAndImport/Views/ExcelOperation/ExportExcelData.cshtml
@{
    ViewData["Title"] = "使用NPOI导出Excel文档";
}
<div class="layui-header header header-doc" spring>
    <div class="layui-main">
        <ul class="layui-nav" id="nav">
            <li class="layui-nav-item">
                <a href="@Url.Action("Index","Home")" style="text-decoration:none;">使用NPOI导出Word文档</a>
            </li>
            <li class="layui-nav-item layui-this">
                <a href="@Url.Action("ExportExcelData","ExcelOperation")" style="text-decoration:none;">使用NPOI导出Excel文档</a>
            </li>
            <li class="layui-nav-item">
                <a href="@Url.Action("Index","ExcelDataImportAndLook")" style="text-decoration:none;">将Excel文档数据数据批量导入到MySQL中</a>
            </li>
        </ul>
    </div>
</div>
<div style="height: 20px;"></div>
<div class="text-center">
    <button type="button" class="layui-btn layui-btn-fluid" title="死数据" onclick="excelExport()" style="width: 400px;">导出并保存如下图所示的Excel文档(死数据)</button>
     <div style="height: 20px;"></div>
 <button type="button" class="layui-btn layui-btn-fluid" title="数据库数据" onclick="excelMSSQLDBExport()" style="width: 400px;">导出并保存如下图所示的Excel文档(数据库数据)</button>
</div>
<div class="layui-card-body">
      <table class="layui-hide" id="layUI_Table"></table>
 </div>
<br />

<img src="~/images/excelPicture.png" height="500" width="100%" />
<script type="text/javascript">
layui.use('table', function () {
          var table = layui.table;
         // 表格渲染
         var tableIns=table.render({
               elem: '#layUI_Table' , 
               url: "@Url.Action("GetUserInfo","ExcelOperation")",
               loading: true,
               height: 505,//容器高度
               limit: 15,
               limits: [15, 30, 60, 90],
               cols: [
                   [
                       { fixed: 'id', type: 'checkbox', width: 100 },
                       { field: 'id', width: 110, title: '用户编号', sort: true },
                       { field: 'userName', width: 150, title: '用户名' },
                       { field: 'sex', width: 70, title: '性别' },
                       { field: 'phone', width: 150, title: '手机号' },
                       { field: 'description', width: 300, title: '个人介绍' },
                       { field: 'hobby', title: '爱好', minWidth: 150, width: 280 }
                   ]
               ],
               page: true
            });

            // 刷新
            $('#btn-refresh').on('click',
                function() {
                    tableIns.reload();
                });
        });
     function excelMSSQLDBExport()
    {
      var index=layer.msg("Excel正在生成数据...",{ icon: 16, shade: 0.8, time: false});
     $.ajax({
            async: true,
         dataType:"json",
         type:"post",
         url:"@Url.Action("DataExportOutPage","ExcelOperation")",
          success: function (res) {
                debugger;
                layer.close(index);
                console.log(res);
                if (res.code == 1) {
                    window.location.href = res.data;
                } else {
                    alert(res.data);
                }
            }
     });
    }


    function excelExport() {
        var index = layer.msg('Excel文档努力生成中...', { icon: 16, shade: 0.8, time: false });
        $.ajax({
            async: true,
            dataType: "json",
            type: "post",
            url: "@Url.Action("DataExportSimple","ExcelOperation")",
            success: function (res) {
                debugger;
                layer.close(index);
                console.log(res);
                if (res.code == 1) {
                    window.location.href = res.data;
                } else {
                    alert(res.data);
                }
            }
        });
    }
</script>